CREATE DATABASE COMPUELECTRIC 
USE COMPUELECTRIC
CREATE TABLE CONTACTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(60) NOT NULL,
    DISTRITO VARCHAR(30) NOT NULL,
    CELULAR VARCHAR(20) NOT NULL
);
SELECT*FROM contacto